services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - PORT=8000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=project_db
      - JWT_EXPIRATION=2592000
      - JWT_SECRET=secret
    working_dir: /app
    command: sh -c "npm install && npm run start:dev"
    tty: true

  db:
    image: postgres:17.4
    volumes:
      - ./data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_DB=project_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres